# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d')),
                ('paixu', models.IntegerField(verbose_name='\u6392\u5e8f')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u4f5c\u54c1\u540d\u79f0')),
                ('thumb', models.ImageField(max_length=200, upload_to='work/', verbose_name='\u4f5c\u54c1\u56fe\u7247')),
                ('spend_time', models.CharField(blank=True, max_length=100, verbose_name='\u9879\u76ee\u5468\u671f')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('paixu', models.IntegerField(default=100, verbose_name='\u6392\u5e8f')),
                ('hits', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Tag', verbose_name='\u6807\u7b7e')),
            ],
        ),
    ]
