# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-10 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='paixu',
            field=models.IntegerField(default=1, verbose_name='\u6392\u5e8f'),
        ),
        migrations.RemoveField(
            model_name='work',
            name='tag',
        ),
        migrations.AddField(
            model_name='work',
            name='tag',
            field=models.ManyToManyField(to='work.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
