# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-10 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180310_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='content',
            field=models.TextField(blank=True, verbose_name='\u9879\u76ee\u8be6\u60c5'),
        ),
        migrations.AddField(
            model_name='work',
            name='linkurl',
            field=models.CharField(blank=True, max_length=120, verbose_name='\u9879\u76ee\u94fe\u63a5'),
        ),
    ]
