# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180310_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '\u4f5c\u54c1', 'verbose_name_plural': '\u4f5c\u54c1'},
        ),
    ]
