# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180310_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=50, verbose_name='\u5206\u7c7b\u540d')),
                ('catname_en', models.CharField(max_length=50, verbose_name='\u5206\u7c7b\u82f1\u6587\u540d')),
                ('paixu', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '\u4f5c\u54c1', 'verbose_name_plural': '\u4f5c\u54c1'},
        ),
        migrations.AddField(
            model_name='work',
            name='desc',
            field=models.CharField(default='\u4eba\u751f\u82e6\u77ed\uff0c\u6211\u7528Python', max_length=255, verbose_name='\u4f5c\u54c1\u7b80\u4ecb'),
        ),
    ]
