# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('desc', models.CharField(max_length=255, verbose_name='\u7b80\u4ecb')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('thumb', models.ImageField(max_length=200, upload_to='article/', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('paixu', models.IntegerField(default=100, verbose_name='\u6392\u5e8f')),
                ('hits', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=50, verbose_name='\u5206\u7c7b\u540d')),
                ('catname_en', models.CharField(max_length=50, verbose_name='\u82f1\u6587\u540d')),
                ('paixu', models.IntegerField(verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
