# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d')),
                ('paixu', models.IntegerField(default=1, verbose_name='\u6392\u5e8f')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u4f5c\u54c1\u540d')),
                ('intro', models.CharField(max_length=255, verbose_name='\u7b80\u4ecb')),
                ('thumb', models.ImageField(max_length=200, upload_to='', verbose_name='\u4f5c\u54c1\u56fe\u72471')),
                ('thumb1', models.ImageField(max_length=200, upload_to='', verbose_name='\u4f5c\u54c1\u56fe\u72472')),
                ('thumb2', models.ImageField(max_length=200, upload_to='', verbose_name='\u4f5c\u54c1\u56fe\u72473')),
                ('content', models.TextField(verbose_name='\u4f5c\u54c1\u4ecb\u7ecd')),
                ('linkurl', models.CharField(max_length=200, verbose_name='\u4f5c\u54c1\u94fe\u63a5')),
                ('paixu', models.IntegerField(default=100, verbose_name='\u6392\u5e8f')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('tags', models.ManyToManyField(to='article.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='\u6587\u7ae0\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=50, verbose_name='\u5206\u7c7b\u540d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='paixu',
            field=models.IntegerField(default=1, verbose_name='\u6392\u5e8f'),
        ),
    ]
