# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180302_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='tags',
            field=models.ManyToManyField(to='article.Tag'),
        ),
    ]
