# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180302_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(max_length=200, upload_to='article/', verbose_name='\u6587\u7ae0\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='category',
            name='paixu',
            field=models.IntegerField(verbose_name='\u6392\u5e8f'),
        ),
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
